### ISSUE TITLE
Convert-to-dynamic task does not remove old workflows

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#1135]
In the new LBR instance, it's not possible to open the old workflows in the workflows admin screen. You get a 500 error.
e.g. https://lbr.csc.fi/api/workflows/33

- [x] Investigate what the problem is
- [x] disable and archive old workflows (using the admin screen?)

```
2019-04-17 09:56:30,152 [ajp-nio-8009-exec-3 lwooller@csc.fi GET /api/workflows/30] ERROR compojure.a
pi.exception - Invalid format: "2015-02-13T14:47:26+02:00" is malformed at "+02:00"
java.lang.IllegalArgumentException: Invalid format: "2015-02-13T14:47:26+02:00" is malformed at "+02:
00"
```

**Comment by foxlynx** [comment]
Whole stacktrace: 
`2019-04-17 09:56:30,152 [ajp-nio-8009-exec-3 lwooller@csc.fi GET /api/workflows/30] ERROR compojure.api.exception - Invalid format: "2015-02-13T14:47:26+02:00" is malformed at "+02:00"
java.lang.IllegalArgumentException: Invalid format: "2015-02-13T14:47:26+02:00" is malformed at "+02:00"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
        at clj_time.format$parse.invokeStatic(format.clj:160)
        at clj_time.format$parse.invoke(format.clj:156)
        at rems.api.workflows$parse_db_time.invokeStatic(workflows.clj:33)
        at rems.api.workflows$parse_db_time.invoke(workflows.clj:32)
        at rems.api.workflows$format_license.invokeStatic(workflows.clj:42)
        at rems.api.workflows$format_license.invoke(workflows.clj:39)
        at clojure.core$map$fn__5851.invoke(core.clj:2753)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:531)
        at clojure.core$seq__5387.invokeStatic(core.clj:137)
        at clojure.core$seq__5387.invoke(core.clj:137)
        at schema.spec.collection$element_transformer$fn__16748.invoke(collection.clj:26)
        at schema.spec.collection.CollectionSpec$fn__16788.invoke(collection.clj:79)
        at schema.spec.collection$element_transformer$fn__16756$fn__16757.invoke(collection.clj:36)
        at schema.core.MapEntry$fn__17575.invoke(core.clj:766)
        at schema.spec.collection$element_transformer$fn__16756.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__16756.invoke(collection.clj:36)
        at schema.spec.collection.CollectionSpec$fn__16788.invoke(collection.clj:79)
        at schema.spec.collection$element_transformer$fn__16756$fn__16757.invoke(collection.clj:36)
        at schema.core$map_elements$iter__17608__17612$fn__17613$fn__17624.invoke(core.clj:815)
        at schema.spec.collection$element_transformer$fn__16756.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__16756.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__16756.invoke(collection.clj:36)
        at schema.spec.collection$element_transformer$fn__16756.invoke(collection.clj:36)
        at schema.spec.collection.CollectionSpec$fn__16788.invoke(collection.clj:79)
        at compojure.api.coercion.schema.SchemaCoercion.coerce_request(schema.clj:62)
        at compojure.api.coercion.schema.SchemaCoercion.coerce_response(schema.clj:75)
        at compojure.api.coercion$coerce_response_BANG_.invokeStatic(coercion.clj:69)
        at compojure.api.coercion$coerce_response_BANG_.invoke(coercion.clj:59)
        at compojure.api.coercion$wrap_coerce_response$fn__29714.invoke(coercion.clj:95)
        at compojure.core$pre_init$fn__26532$fn__26535.invoke(core.clj:335)
        at compojure.core$wrap_route_middleware$fn__26463.invoke(core.clj:127)
        at compojure.core$wrap_route_info$fn__26468.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__26472.invoke(core.clj:146)
        at compojure.core$wrap_routes$fn__26542.invoke(core.clj:348)
        at compojure.api.routes.Route.invoke(routes.clj:90)
        at compojure.core$routing$fn__26487.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__26491.invoke(core.clj:192)
        at compojure.api.compojure_compat$make_context$handler__31383.invoke(compojure_compat.clj:26)
        at compojure.api.compojure_compat$make_context$fn__31385.invoke(compojure_compat.clj:34)
        at compojure.api.routes.Route.invoke(routes.clj:90)
        at compojure.core$routing$fn__26487.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__26491.invoke(core.clj:192)
        at compojure.core$routing$fn__26487.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__26491.invoke(core.clj:192)
        at compojure.core$make_context$handler__26519.invoke(core.clj:285)
        at compojure.core$make_context$fn__26521.invoke(core.clj:293)
        at compojure.api.routes.Route.invoke(routes.clj:90)
        at compojure.core$routing$fn__26487.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__26491.invoke(core.clj:192)
        at compojure.api.routes.Route.invoke(routes.clj:90)
        at ring.swagger.middleware$wrap_swagger_data$fn__31727.invoke(middleware.clj:35)
        at rems.api$transaction_middleware$fn__32976.invoke(api.clj:75)
        at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:171)
        at ring.middleware.cors$handle_cors.invoke(cors.clj:160)
        at ring.middleware.cors$wrap_cors$fn__32951.invoke(cors.clj:185)
        at compojure.api.middleware$wrap_swagger_data$fn__30772.invoke(middleware.clj:190)
        at compojure.api.middleware$wrap_inject_data$fn__30750.invoke(middleware.clj:96)
        at muuntaja.middleware$wrap_params$fn__29871.invoke(middleware.clj:52)
        at compojure.api.middleware$wrap_exceptions$fn__30739.invoke(middleware.clj:62)
        at muuntaja.middleware$wrap_format_request$fn__29883.invoke(middleware.clj:114)
        at compojure.api.middleware$wrap_exceptions$fn__30739.invoke(middleware.clj:62)
        at muuntaja.middleware$wrap_format_response$fn__29887.invoke(middleware.clj:132)
        at muuntaja.middleware$wrap_format_negotiate$fn__29880.invoke(middleware.clj:96)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__29752.invoke(keyword_params.clj:53)
        at ring.middleware.nested_params$wrap_nested_params$fn__29802.invoke(nested_params.clj:89)
        at ring.middleware.params$wrap_params$fn__29850.invoke(params.clj:67)
        at compojure.api.middleware$wrap_inject_data$fn__30750.invoke(middleware.clj:96)
        at compojure.api.routes.Route.invoke(routes.clj:90)
        at clojure.lang.Var.invoke(Var.java:384)
        at compojure.core$routing$fn__26487.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__26491.invoke(core.clj:192)
        at compojure.core$routing$fn__26487.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__26491.invoke(core.clj:192)
        at rems.middleware$wrap_unauthorized_and_forbidden$fn__34559.invoke(middleware.clj:172)
        at rems.middleware$wrap_logging$fn__34562.invoke(middleware.clj:191)
        at rems.middleware$wrap_i18n$fn__34552.invoke(middleware.clj:154)
        at taoensso.tempura$wrap_ring_request$fn__15420.invoke(tempura.cljc:398)
        at rems.middleware$wrap_tempura_locales_from_session$fn__34548.invoke(middleware.clj:139)
        at rems.middleware$wrap_role_headers$fn__34516.invoke(middleware.clj:91)
        at rems.middleware$wrap_context$fn__34511$fn__34512.invoke(middleware.clj:87)
        at rems.logging$with_mdc_STAR_.invokeStatic(logging.clj:21)
        at rems.logging$with_mdc_STAR_.invoke(logging.clj:9)
        at rems.middleware$wrap_context$fn__34511.invoke(middleware.clj:86)
        at rems.middleware$wrap_user$fn__34504$fn__34505.invoke(middleware.clj:77)
        at rems.logging$with_mdc_STAR_.invokeStatic(logging.clj:21)
        at rems.logging$with_mdc_STAR_.invoke(logging.clj:9)
        at rems.middleware$wrap_user$fn__34504.invoke(middleware.clj:76)
        at ring.middleware.anti_forgery$wrap_anti_forgery$fn__15624.invoke(anti_forgery.clj:94)
        at rems.middleware$wrap_api_key_or_csrf_token$fn__34501.invoke(middleware.clj:63)
        at buddy.auth.middleware$wrap_authentication$fn__26865.invoke(middleware.clj:59)
        at buddy.auth.middleware$wrap_authorization$fn__26872.invoke(middleware.clj:110)
        at ring.middleware.webjars$wrap_webjars$fn__34488.invoke(webjars.clj:40)
        at ring.middleware.flash$wrap_flash$fn__33316.invoke(flash.clj:39)
        at ring.middleware.session$wrap_session$fn__33472.invoke(session.clj:108)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__29752.invoke(keyword_params.clj:53)
        at ring.middleware.nested_params$wrap_nested_params$fn__29802.invoke(nested_params.clj:89)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__32310.invoke(multipart_params.clj:173)
        at ring.middleware.params$wrap_params$fn__29850.invoke(params.clj:67)
        at ring.middleware.cookies$wrap_cookies$fn__33435.invoke(cookies.clj:175)
        at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__33541.invoke(absolute_redirects.clj:47)
        at ring.middleware.resource$wrap_resource_prefer_resources$fn__33482.invoke(resource.clj:25)
        at ring.middleware.content_type$wrap_content_type$fn__31780.invoke(content_type.clj:34)
        at ring.middleware.default_charset$wrap_default_charset$fn__33521.invoke(default_charset.clj:31)
        at ring.middleware.not_modified$wrap_not_modified$fn__31805.invoke(not_modified.clj:61)
        at ring.middleware.x_headers$wrap_x_header$fn__33287.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__33287.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__33287.invoke(x_headers.clj:22)
        at rems.middleware$wrap_internal_error$fn__34539.invoke(middleware.clj:111)
        at rems.middleware$wrap_i18n$fn__34552.invoke(middleware.clj:154)
        at taoensso.tempura$wrap_ring_request$fn__15420.invoke(tempura.cljc:398)
        at rems.middleware$wrap_tempura_locales_from_session$fn__34548.invoke(middleware.clj:139)
        at ring.middleware.format_params$wrap_format_params$fn__34215.invoke(format_params.clj:119)
        at ring.middleware.format_params$wrap_format_params$fn__34215.invoke(format_params.clj:119)
        at ring.middleware.format_params$wrap_format_params$fn__34215.invoke(format_params.clj:119)
        at ring.middleware.format_response$wrap_format_response$fn__34384.invoke(format_response.clj:194)
        at rems.middleware$wrap_formats$fn__34543.invoke(middleware.clj:125)
        at rems.middleware$wrap_request_context$fn__34571$fn__34572.invoke(middleware.clj:200)
        at rems.logging$with_mdc_STAR_.invokeStatic(logging.clj:21)
        at rems.logging$with_mdc_STAR_.invoke(logging.clj:9)
        at rems.middleware$wrap_request_context$fn__34571.invoke(middleware.clj:198)
        at clojure.lang.Var.invoke(Var.java:384)
        at rems.listener$_contextInitialized$fn__11.invoke(listener.clj:1)
        at ring.util.servlet$make_blocking_service_method$fn__35658.invoke(servlet.clj:113)
        at rems.servlet$_service.invokeStatic(servlet.clj:1)
        at rems.servlet$_service.invoke(servlet.clj:1)
        at rems.servlet.service(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by foxlynx** [comment]
And the api call https://rems-lbr03.csc.fi/api/workflows/30 returns:
`{
  "type": "unknown-exception",
  "class": "java.lang.IllegalArgumentException"
}`
