### ISSUE TITLE
Auth0 oidc erro after authentication

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#1837]
Dear REMS team,

I am getting an error while testing the Auth0 oidc authentication.

I can see the oidc login page which redirects me to the auth0 application login page but when I put my credentials, rems gives me a 500 error

This is what I can see in the rems logs
```
2019-12-02 01:28:55,957 [qtp1279547787-21 - GET /js/out/cljsjs/development/emotion.umd.min.js.map] INFO  rems.middleware - > :get /js/out/cljsjs/development/emotion.umd.min.js.map lang: :en user: nil  roles: nil
2019-12-02 01:28:56,020 [qtp1279547787-21 - GET /js/out/cljsjs/development/emotion.umd.min.js.map] INFO  rems.middleware - < :get /js/out/cljsjs/development/emotion.umd.min.js.map 200
2019-12-02 01:28:58,052 [qtp1279547787-17 - GET /oidc-login] INFO  rems.middleware - > :get /oidc-login lang: :en user: nil  roles: nil
2019-12-02 01:28:58,060 [qtp1279547787-17 - GET /oidc-login] INFO  rems.middleware - < :get /oidc-login 302 https://dev-zwxmwkn0.au.auth0.com/authorize?response_type=code&client_id=66LnIETyplrqf0pjw71DagL6CnepOjKj&redirect_uri=http://129.94.14.234:3000/oidc-callback&scope=openid profile email
2019-12-02 01:29:12,692 [qtp1279547787-20 - GET /oidc-callback] INFO  rems.middleware - > :get /oidc-callback?code=-ecNmZ-djarSI77U lang: :en user: nil  roles: nil
Dec 02, 2019 1:29:12 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: did=s%3Av0%3A2560b120-14a3-11ea-b220-b778d60a3533.qFWToGwv2UX5GmWw9NRL%2FadYSjRX7zWeWl6tvYPTN%2F4; Max-Age=157788000; Path=/; Expires=Sun, 01 Dec 2024 07:29:12 GMT; HttpOnly; Secure". Invalid 'expires' attribute: Sun, 01 Dec 2024 07:29:12 GMT
2019-12-02 01:29:12,930 [qtp1279547787-20 - GET /oidc-callback] ERROR rems.middleware - Internal error
com.auth0.jwt.exceptions.AlgorithmMismatchException: The provided Algorithm doesn't match the one defined in the JWT's Header.
        at com.auth0.jwt.JWTVerifier.verifyAlgorithm(JWTVerifier.java:393)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:385)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:370)
        at rems.jwt$validate.invokeStatic(jwt.clj:39)
        at rems.jwt$validate.invoke(jwt.clj:28)
        at rems.auth.oidc$oidc_callback.invokeStatic(oidc.clj:40)
        at rems.auth.oidc$oidc_callback.invoke(oidc.clj:22)
        at rems.auth.oidc$fn__40061.invokeStatic(oidc.clj:61)
        at rems.auth.oidc$fn__40061.invoke(oidc.clj:61)
        at compojure.core$wrap_response$fn__33288.invoke(core.clj:158)
        at compojure.core$wrap_route_middleware$fn__33272.invoke(core.clj:128)
        at compojure.core$wrap_route_info$fn__33277.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__33281.invoke(core.clj:146)
        at compojure.core$routing$fn__33296.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__33300.invoke(core.clj:192)
        at compojure.core$routing$fn__33296.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__33300.invoke(core.clj:192)
        at compojure.core$routing$fn__33296.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__33300.invoke(core.clj:192)
        at compojure.core$routing$fn__33296.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__33300.invoke(core.clj:192)
        at compojure.core$routing$fn__33296.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2701)
        at clojure.core$some.invoke(core.clj:2692)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at compojure.core$routes$fn__33300.invoke(core.clj:192)
        at ring.middleware.reload$wrap_reload$fn__42095.invoke(reload.clj:39)
        at rems.middleware$wrap_unauthorized_and_forbidden$fn__43972.invoke(middleware.clj:162)
        at rems.middleware$wrap_logging$fn__43975.invoke(middleware.clj:184)
        at rems.middleware$wrap_i18n$fn__43966.invoke(middleware.clj:145)
        at rems.middleware$wrap_role_headers$fn__43925.invoke(middleware.clj:92)
        at rems.middleware$wrap_context$fn__43920$fn__43921.invoke(middleware.clj:88)
        at rems.logging$with_mdc_STAR_.invokeStatic(logging.clj:21)
        at rems.logging$with_mdc_STAR_.invoke(logging.clj:9)
        at rems.middleware$wrap_context$fn__43920.invoke(middleware.clj:87)
        at rems.middleware$wrap_user$fn__43913$fn__43914.invoke(middleware.clj:79)
        at rems.logging$with_mdc_STAR_.invokeStatic(logging.clj:21)
        at rems.logging$with_mdc_STAR_.invoke(logging.clj:9)
        at rems.middleware$wrap_user$fn__43913.invoke(middleware.clj:78)
        at ring.middleware.anti_forgery$wrap_anti_forgery$fn__39885.invoke(anti_forgery.clj:94)
        at rems.middleware$wrap_api_key_or_csrf_token$fn__43910.invoke(middleware.clj:65)
        at buddy.auth.middleware$wrap_authentication$fn__38994.invoke(middleware.clj:59)
        at buddy.auth.middleware$wrap_authorization$fn__39001.invoke(middleware.clj:110)
        at ring.middleware.webjars$wrap_webjars$fn__43895.invoke(webjars.clj:40)
        at ring.middleware.flash$wrap_flash$fn__42465.invoke(flash.clj:39)
        at ring.middleware.session$wrap_session$fn__42647.invoke(session.clj:108)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__35819.invoke(keyword_params.clj:53)
        at ring.middleware.nested_params$wrap_nested_params$fn__35877.invoke(nested_params.clj:89)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__37731.invoke(multipart_params.clj:173)
        at ring.middleware.params$wrap_params$fn__35951.invoke(params.clj:67)
        at ring.middleware.cookies$wrap_cookies$fn__42598.invoke(cookies.clj:175)
        at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__42748.invoke(absolute_redirects.clj:47)
        at ring.middleware.resource$wrap_resource_prefer_resources$fn__42665.invoke(resource.clj:25)
        at ring.middleware.content_type$wrap_content_type$fn__37049.invoke(content_type.clj:34)
        at ring.middleware.default_charset$wrap_default_charset$fn__42720.invoke(default_charset.clj:31)
        at ring.middleware.not_modified$wrap_not_modified$fn__37082.invoke(not_modified.clj:61)
        at ring.middleware.x_headers$wrap_x_header$fn__42428.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__42428.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__42428.invoke(x_headers.clj:22)
        at rems.middleware$wrap_internal_error$fn__43948.invoke(middleware.clj:112)
        at ring.middleware.format_params$wrap_format_params$fn__43606.invoke(format_params.clj:92)
        at ring.middleware.format_params$wrap_format_params$fn__43606.invoke(format_params.clj:92)
        at ring.middleware.format_params$wrap_format_params$fn__43606.invoke(format_params.clj:92)
        at ring.middleware.format_response$wrap_format_response$fn__43783.invoke(format_response.clj:194)
        at rems.middleware$wrap_formats$fn__43961.invoke(middleware.clj:127)
        at rems.middleware$wrap_request_context$fn__43984$fn__43985.invoke(middleware.clj:193)
        at rems.logging$with_mdc_STAR_.invokeStatic(logging.clj:21)
        at rems.logging$with_mdc_STAR_.invoke(logging.clj:9)
        at rems.middleware$wrap_request_context$fn__43984.invoke(middleware.clj:191)
        at ring.adapter.jetty$proxy_handler$fn__2490.invoke(jetty.clj:26)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
2019-12-02 01:29:13,130 [qtp1279547787-22 - GET /css/en/screen.css] INFO  rems.middleware - > :get /css/en/screen.css lang: :en user: nil  roles: nil
2019-12-02 01:29:13,134 [qtp1279547787-22 - GET /css/en/screen.css] INFO  rems.home - Rendering stylesheet for language :en
2019-12-02 01:29:13,213 [qtp1279547787-22 - GET /css/en/screen.css] INFO  rems.middleware - < :get /css/en/screen.css 200
```

please advise

thank you

**Comment by luontola** [comment]
Rems expects Auth0 to use RSA256 as the JWT's signing algorithm. Maybe your Auth0 is configured to use HS256 instead? https://auth0.com/docs/tokens/concepts/signing-algorithms
