### ISSUE TITLE
rems docker container not starting

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#2006]
Dear REMS community,

I am trying to start the rems containers following the documentation, however it crashes:

```
[mansop@reims rems]$ docker-compose up -d db
Creating network "rems_default" with the default driver
Creating rems_db_1 ... done
[mansop@reims rems]$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
4bcb7cf7f0ad        postgres:9.6        "docker-entrypoint..."   27 seconds ago      Up 25 seconds       127.0.0.1:5432->5432/tcp   rems_db_1
[mansop@reims rems]$ docker-compose run --rm app migrate
./docker-entrypoint.sh: line 3: cd: rems: No such file or directory
####################
########## RUNNING COMMAND: exec java --illegal-access=deny -Drems.config=config/config.edn -jar rems.jar
####################
2020-02-19 02:02:47,444 [main - - -] INFO  org.eclipse.jetty.util.log - Logging initialized @4317ms to org.eclipse.jetty.util.log.Slf4jLog
2020-02-19 02:02:56,877 [main - - -] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2020-02-19 02:02:57,189 [main - - -] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2020-02-19 02:03:00,763 [main - - -] INFO  org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 11.0.6+10
2020-02-19 02:03:00,787 [main - - -] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@4acca937{HTTP/1.1,[http/1.1]}{0.0.0.0:3000}
2020-02-19 02:03:00,787 [main - - -] INFO  org.eclipse.jetty.server.Server - Started @17662ms
2020-02-19 02:03:00,788 [main - - -] INFO  luminus.http-server - server started on port 3000
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.config/env started
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.config/oidc-configuration started
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.db.core/*db* started
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.locales/translations started
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.db.applications/all-applications-cache started
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.db.applications/all-applications-cache-reloader started
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.db.entitlements/entitlement-poller started
2020-02-19 02:03:00,789 [main - - -] INFO  rems.standalone - #'rems.email.core/email-poller started
2020-02-19 02:03:00,792 [main - - -] INFO  rems.standalone - #'rems.application.search/search-index started
2020-02-19 02:03:00,792 [main - - -] INFO  rems.standalone - #'rems.jwt/jwk-provider started
2020-02-19 02:03:00,801 [main - - -] INFO  rems.standalone - #'rems.css.styles/rendered-css-files started
2020-02-19 02:03:00,801 [main - - -] INFO  rems.standalone - #'rems.home/memoized-render-css started
2020-02-19 02:03:00,801 [main - - -] INFO  rems.standalone - #'rems.handler/handler started
2020-02-19 02:03:00,801 [main - - -] INFO  rems.standalone - #'rems.standalone/http-server started
2020-02-19 02:03:00,801 [main - - -] INFO  rems.standalone - #'rems.standalone/repl-server started
2020-02-19 02:03:00,801 [main - - -] INFO  rems.validate - Validating data
2020-02-19 02:03:00,856 [main - - -] ERROR rems.validate - Validations failed
java.lang.Exception: Exception in :get-form-templates
        at conman.core$try_query$fn__21566$fn__21567.invoke(core.clj:32)
        at rems.db.core$fn__25197$f__21594__auto____25224.invoke(core.clj:18)
        at rems.db.form$get_form_templates.invokeStatic(form.clj:32)
        at rems.db.form$get_form_templates.invoke(form.clj:31)
        at rems.validate$validate_forms.invokeStatic(validate.clj:20)
        at rems.validate$validate_forms.invoke(validate.clj:19)
        at rems.validate$validate.invokeStatic(validate.clj:46)
        at rems.validate$validate.invoke(validate.clj:43)
        at rems.standalone$start_app.invokeStatic(standalone.clj:60)
        at rems.standalone$start_app.doInvoke(standalone.clj:53)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at rems.standalone$_main.invokeStatic(standalone.clj:123)
        at rems.standalone$_main.doInvoke(standalone.clj:63)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at rems.standalone.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "form_template" does not exist
  Position: 82
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1062)
        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1056)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1086)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1065)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1155)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1117)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1133)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1117)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:660)
        at hugsql.adapter.clojure_java_jdbc.HugsqlAdapterClojureJavaJdbc.query(clojure_java_jdbc.clj:15)
        at hugsql.adapter$fn__21205$G__21129__21210.invoke(adapter.clj:3)
        at hugsql.adapter$fn__21205$G__21128__21216.invoke(adapter.clj:3)
        at clojure.lang.Var.invoke(Var.java:399)
        at hugsql.core$db_fn_STAR_$y__21502.doInvoke(core.clj:458)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at hugsql.core$db_fn_STAR_$y__21502.invoke(core.clj:448)
        at conman.core$try_query$fn__21566$fn__21567.invoke(core.clj:30)
        ... 20 common frames omitted
2020-02-19 02:03:00,856 [main - - -] INFO  rems.standalone - Refreshing caches
Exception in thread "main" java.lang.Exception: Exception in :get-application-events-since
        at conman.core$try_query$fn__21566$fn__21567.invoke(core.clj:32)
        at rems.db.core$fn__25197$f__21594__auto____25224.invoke(core.clj:18)
        at rems.db.events$get_all_events_since.invokeStatic(events.clj:53)
        at rems.db.events$get_all_events_since.invoke(events.clj:52)
        at rems.application.events_cache$update_with_new_events$fn__26203.invoke(events_cache.clj:18)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:759)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:824)
...
```

any thoughts?

thank you

**Comment by Macroz** [comment]
Perhaps you are not running a properly initialized database. It is missing the basic tables. I.e. the `lein run migrate` part at least.

```
Caused by: org.postgresql.util.PSQLException: ERROR: relation "form_template" does not exist
```

**Comment by Masber** [comment]
yes I had to run migrate to make it work, thank you
