### ISSUE TITLE
Problems running with docker

### ISSUE THREAD

**Issue by MalinAhlberg** [CSCfi/rems#2237]
Hi,

I try to run the [docker-compose setup](https://github.com/CSCfi/rems/blob/master/docs/development.md#running-the-application-with-docker) of the system, but I run into some problems. Not sure what I'm doing wrong.

I use Ubuntu 18.04.3, Docker version 18.09.7.

Running the system using the "full development documentation" works fine, but the docker-compose setup gives me the following problems:

1. The `.dockerignore` file does not work as intended. I get `COPY failed: stat /var/lib/docker/tmp/docker-builder167406263/target/uberjar/rems.jar: no such file or directory`.
If I remove the initial `/` at the last line (so I get `!target/uberjar/rems.jar`), it works, however.
After that, I can build and start the db.

2. When runnig `docker-compose run --rm app migrate`, I get an error `./docker-entrypoint.sh: line 3: cd: rems: No such file or directory` at the beginning (I guess since the workdir is already set to /rems?). Even if this doesn't make it crash, it's a bit confusing getting an error message first thing :) 

3. After that, I keep getting errors like this one:
```
2020-06-16 12:46:22,324 [pool-3-thread-1 - - -] ERROR rems.scheduler - Internal error 
java.lang.Exception: Exception in :get-outbox
	at conman.core$try_query$fn__13989$fn__13990.invoke(core.clj:32)
	at rems.db.core$fn__14090$f__14017__auto____14117.invoke(core.clj:38)
	at rems.db.outbox$get_entries.invokeStatic(outbox.clj:72)
	at rems.db.outbox$get_entries.invoke(outbox.clj:68)
	at rems.db.outbox$get_due_entries.invokeStatic(outbox.clj:78)
	at rems.db.outbox$get_due_entries.invoke(outbox.clj:77)
	at rems.db.entitlements$process_outbox_BANG_.invokeStatic(entitlements.clj:98)
	at rems.db.entitlements$process_outbox_BANG_.invoke(entitlements.clj:96)
	at rems.scheduler$start_BANG_$task__28772.invoke(scheduler.clj:11)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "outbox" does not exist
  Position: 34
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1062)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1056)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1086)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1065)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1155)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1117)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1133)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1117)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:660)
	at hugsql.adapter.clojure_java_jdbc.HugsqlAdapterClojureJavaJdbc.query(clojure_java_jdbc.clj:15)
	at hugsql.adapter$fn__13714$G__13638__13719.invoke(adapter.clj:3)
	at hugsql.adapter$fn__13714$G__13637__13725.invoke(adapter.clj:3)
	at clojure.lang.Var.invoke(Var.java:399)
	at hugsql.core$db_fn_STAR_$y__13925.doInvoke(core.clj:458)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at hugsql.core$db_fn_STAR_$y__13925.invoke(core.clj:448)
	at conman.core$try_query$fn__13989$fn__13990.invoke(core.clj:30)
	... 15 common frames omitted
2020-06-16 12:46:32,329 [pool-5-thread-1 - - -] ERROR rems.scheduler - Internal error 
java.lang.Exception: Exception in :get-outbox
	at conman.core$try_query$fn__13989$fn__13990.invoke(core.clj:32)
	at rems.db.core$fn__14090$f__14017__auto____14117.invoke(core.clj:38)
	at rems.db.outbox$get_entries.invokeStatic(outbox.clj:72)
	at rems.db.outbox$get_entries.invoke(outbox.clj:68)
	at rems.db.outbox$get_due_entries.invokeStatic(outbox.clj:78)
	at rems.db.outbox$get_due_entries.invoke(outbox.clj:77)
	at rems.email.core$try_send_emails_BANG_.invokeStatic(core.clj:117)
	at rems.email.core$try_send_emails_BANG_.invoke(core.clj:116)
	at rems.scheduler$start_BANG_$task__28772.invoke(scheduler.clj:11)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "outbox" does not exist
  Position: 34
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1062)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1056)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1086)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1065)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1155)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1117)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1133)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1117)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:660)
	at hugsql.adapter.clojure_java_jdbc.HugsqlAdapterClojureJavaJdbc.query(clojure_java_jdbc.clj:15)
	at hugsql.adapter$fn__13714$G__13638__13719.invoke(adapter.clj:3)
	at hugsql.adapter$fn__13714$G__13637__13725.invoke(adapter.clj:3)
	at clojure.lang.Var.invoke(Var.java:399)
	at hugsql.core$db_fn_STAR_$y__13925.doInvoke(core.clj:458)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at hugsql.core$db_fn_STAR_$y__13925.invoke(core.clj:448)
	at conman.core$try_query$fn__13989$fn__13990.invoke(core.clj:30)
	... 15 common frames omitted
```

**Comment by opqdonut** [comment]
Hi, and sorry for the slow reply.

The error in 3. is due to database tables missing, which is due to the migrate command failing in 2. Thanks for the report! Looks like our docker-compose setup needs some more love, ping @vvaltia.

**Comment by opqdonut** [comment]
I just created a PR (see above) that fixes the docker-compose instructions. These worked for me with docker 19.03.12 and docker-compose 1.25.0. I didn't need to fix the `.dockerignore` file, and the docker docs claim that `/pattern` is the same as `pattern` in the dockerignore file.

Hope this helps!

**Comment by MalinAhlberg** [comment]
Yes, works better now, thanks!

**Comment by opqdonut** [comment]
Great, I'll close this ticket then. We'll probably have some more improvements to docker stuff later this autumn. We also plan to publish images on dockerhub.
