### ISSUE TITLE
Swagger UI attachments

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2851]
Swagger UI does not allow adding attachments because the file upload field does not work. Perhaps upgrading the version or double-checking the type annotations would help. It could be a compojure-api problem too.

**Comment by nuwang** [comment]
I believe I ran into the same issue when trying to generate a python-client as follows:
```bash
 docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i https://rems-demo.rahtiapp.fi/swagger.json -l python -o /local/python
 ```
 
 The reported error may provide more context as to the cause:
 ```
[main] ERROR io.swagger.codegen.DefaultCodegen - Cannot use Parameter io.swagger.models.parameters.RefParameter@673ed699 as Body Parameter
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: applications
	description: null
	externalDocs: null
	extensions:{}}
  Operation: null
  Resource: post /api/applications/add-attachment
  Definitions: {AcceptInvitationResponse=io.swagger.models.ModelImpl@160e57b3, AcceptInvitationResponseWorkflow=io.swagger.models.ModelImpl@3e37c467, AcceptInvitationResult=io.swagger.models.ModelImpl@20c4ab6d, AcceptLicensesCommand=io.swagger.models.ModelImpl@c41d6d20, AddLicensesCommand=io.swagger.models.ModelImpl@71e49aa, AddMemberCommand=io.swagger.models.ModelImpl@12a3937a, Applicant=io.swagger.models.ModelImpl@d1e58a2f, Application=io.swagger.models.ModelImpl@b41b289d, ApplicationAcceptedLicenses=io.swagger.models.ModelImpl@c9bd82bb, ApplicationAttachment=io.swagger.models.ModelImpl@a6b17cc2, ApplicationBlacklistResource=io.swagger.models.ModelImpl@f6f99b6f, ApplicationCopiedFrom=io.swagger.models.ModelImpl@80bd47c7, ApplicationCopiedTo=io.swagger.models.ModelImpl@80bd47c7, ApplicationFormsFieldsColumns=io.swagger.models.ModelImpl@f38cb1e7, ApplicationFormsFieldsOptions=io.swagger.models.ModelImpl@f38cb1e7, ApplicationFormsFieldsPreviousValue=io.swagger.models.ModelImpl@47a9fe77, ApplicationFormsFieldsValue=io.swagger.models.ModelImpl@47a9fe77, ApplicationFormsFieldsVisibility=io.swagger.models.ModelImpl@7d6adb5, ApplicationFormsFieldsVisibilityField=io.swagger.models.ModelImpl@bc66748f, ApplicationInvitedMembers=io.swagger.models.ModelImpl@424b6a0d, ApplicationOverview=io.swagger.models.ModelImpl@cacf401b, ApplicationRaw=io.swagger.models.ModelImpl@abb199f0, ApplicationRawAcceptedLicenses=io.swagger.models.ModelImpl@c9bd82bb, ApplicationRawBlacklistResource=io.swagger.models.ModelImpl@f6f99b6f, ApplicationRawCopiedFrom=io.swagger.models.ModelImpl@80bd47c7, ApplicationRawCopiedTo=io.swagger.models.ModelImpl@80bd47c7, ApplicationRawFormsFieldsColumns=io.swagger.models.ModelImpl@f38cb1e7, ApplicationRawFormsFieldsOptions=io.swagger.models.ModelImpl@f38cb1e7, ApplicationRawFormsFieldsPreviousValue=io.swagger.models.ModelImpl@47a9fe77, ApplicationRawFormsFieldsValue=io.swagger.models.ModelImpl@47a9fe77, ApplicationRawFormsFieldsVisibility=io.swagger.models.ModelImpl@924c211d, ApplicationRawFormsFieldsVisibilityField=io.swagger.models.ModelImpl@bc66748f, ApplicationRawInvitedMembers=io.swagger.models.ModelImpl@424b6a0d, ApplicationRawResourcesDuo=io.swagger.models.ModelImpl@1671c6e0, ApplicationRawResourcesDuoCodesRestrictions=io.swagger.models.ModelImpl@20fb4438, ApplicationRawResourcesDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, ApplicationRawRolePermissions=io.swagger.models.ModelImpl@613551d9, ApplicationRawUserRoles=io.swagger.models.ModelImpl@613551d9, ApplicationRawWorkflow=io.swagger.models.ModelImpl@fef38469, ApplicationResourcesDuo=io.swagger.models.ModelImpl@1671c6e0, ApplicationResourcesDuoCodesRestrictions=io.swagger.models.ModelImpl@ddef813a, ApplicationResourcesDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, ApplicationWorkflow=io.swagger.models.ModelImpl@fef38469, ApproveCommand=io.swagger.models.ModelImpl@c540f1ed, ArchivedCommand=io.swagger.models.ModelImpl@f84a57e0, AssignExternalIdCommand=io.swagger.models.ModelImpl@7ec70623, AttachmentMetadata=io.swagger.models.ModelImpl@6f439a67, AuditLogEntry=io.swagger.models.ModelImpl@3e19b4f, AvailableActor=io.swagger.models.ModelImpl@6605d417, AvailableOwner=io.swagger.models.ModelImpl@6605d417, BlacklistCommand=io.swagger.models.ModelImpl@6bf78824, BlacklistCommandResource=io.swagger.models.ModelImpl@f6f99b6f, BlacklistEntry=io.swagger.models.ModelImpl@e1869785, BlacklistEntryWithDetails=io.swagger.models.ModelImpl@6f11ecbd, CatalogueItem=io.swagger.models.ModelImpl@55edc1e5, CatalogueItemLocalization=io.swagger.models.ModelImpl@d56d7296, CatalogueItemLocalizations=io.swagger.models.ModelImpl@dda591db, CatalogueItemLocalizationsKeyword3764=io.swagger.models.ModelImpl@367d7fac, Category=io.swagger.models.ModelImpl@ee4d5f11, CategoryFull=io.swagger.models.ModelImpl@8d1464cc, CategoryId=io.swagger.models.ModelImpl@89de610b, CategoryTree=io.swagger.models.ModelImpl@e12a5625, ChangeApplicantCommand=io.swagger.models.ModelImpl@c05287c4, ChangeFormCommand=io.swagger.models.ModelImpl@f3f7ff1, ChangeFormResponse=io.swagger.models.ModelImpl@7072b286, ChangeResourcesCommand=io.swagger.models.ModelImpl@8fe3d28a, CloseCommand=io.swagger.models.ModelImpl@ae9f1fcd, CommandAttachment=io.swagger.models.ModelImpl@d0c0f6df, CopyAsNewCommand=io.swagger.models.ModelImpl@b847303b, CopyAsNewResponse=io.swagger.models.ModelImpl@51687add, CreateApplicationCommand=io.swagger.models.ModelImpl@9e377d30, CreateApplicationResponse=io.swagger.models.ModelImpl@6b03a0af, CreateCatalogueItemCommand=io.swagger.models.ModelImpl@e805c391, CreateCatalogueItemResponse=io.swagger.models.ModelImpl@f081d30, CreateCategoryCommand=io.swagger.models.ModelImpl@10c2eb3d, CreateFormCommand=io.swagger.models.ModelImpl@5dbafa56, CreateFormCommandFieldsColumns=io.swagger.models.ModelImpl@f38cb1e7, CreateFormCommandFieldsOptions=io.swagger.models.ModelImpl@f38cb1e7, CreateFormCommandFieldsVisibility=io.swagger.models.ModelImpl@9eb37829, CreateFormCommandFieldsVisibilityField=io.swagger.models.ModelImpl@bc66748f, CreateFormResponse=io.swagger.models.ModelImpl@f081d30, CreateInvitationCommand=io.swagger.models.ModelImpl@e96bb6c7, CreateInvitationResponse=io.swagger.models.ModelImpl@46b92626, CreateLicenseCommand=io.swagger.models.ModelImpl@4f5f83c3, CreateLicenseResponse=io.swagger.models.ModelImpl@f081d30, CreateOrganizationCommand=io.swagger.models.ModelImpl@2301978b, CreateOrganizationCommandReviewEmails=io.swagger.models.ModelImpl@385ad7ab, CreateOrganizationResponse=io.swagger.models.ModelImpl@c3f1a3fe, CreateResourceCommand=io.swagger.models.ModelImpl@4e26b56d, CreateResourceCommandDuo=io.swagger.models.ModelImpl@723d80c2, CreateResourceCommandDuoCodesRestrictions=io.swagger.models.ModelImpl@d16f3c, CreateResourceCommandDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, CreateResourceResponse=io.swagger.models.ModelImpl@f081d30, CreateUserCommand=io.swagger.models.ModelImpl@b8d8fdd5, CreateWorkflowCommand=io.swagger.models.ModelImpl@ca1efa12, CreateWorkflowCommandForms=io.swagger.models.ModelImpl@6df904bf, CreateWorkflowResponse=io.swagger.models.ModelImpl@f081d30, DecideCommand=io.swagger.models.ModelImpl@5436897, Decider=io.swagger.models.ModelImpl@109b7d6e, DeleteCategoryCommand=io.swagger.models.ModelImpl@89de610b, DeleteCommand=io.swagger.models.ModelImpl@f02b83, DeleteEGAApiKeyResponse=io.swagger.models.ModelImpl@99ab9390, DuoCode=io.swagger.models.ModelImpl@9a5f6bf6, DuoCodeFull=io.swagger.models.ModelImpl@9162a69d, EditCatalogueItemCommand=io.swagger.models.ModelImpl@7ce68a51, EditFormCommand=io.swagger.models.ModelImpl@46d19070, EditFormCommandFieldsColumns=io.swagger.models.ModelImpl@f38cb1e7, EditFormCommandFieldsOptions=io.swagger.models.ModelImpl@f38cb1e7, EditFormCommandFieldsVisibility=io.swagger.models.ModelImpl@c71e9a3b, EditFormCommandFieldsVisibilityField=io.swagger.models.ModelImpl@bc66748f, EditOrganizationCommand=io.swagger.models.ModelImpl@89e7fbb9, EditOrganizationCommandReviewEmails=io.swagger.models.ModelImpl@385ad7ab, EditOrganizationResponse=io.swagger.models.ModelImpl@888b19d2, EditWorkflowCommand=io.swagger.models.ModelImpl@1bb7746b, EnabledCommand=io.swagger.models.ModelImpl@a92a863e, Entitlement=io.swagger.models.ModelImpl@d77934eb, Event=io.swagger.models.ModelImpl@8d33f2f6, ExtraPage=io.swagger.models.ModelImpl@f7618614, ExtraPageResponse=io.swagger.models.ModelImpl@d005a7f1, Field=io.swagger.models.ModelImpl@c5f470c7, FieldTemplate=io.swagger.models.ModelImpl@70cdacea, Form=io.swagger.models.ModelImpl@5f2d80f, FormTemplate=io.swagger.models.ModelImpl@c4a8a0f6, FormTemplateErrors=io.swagger.models.ModelImpl@9ecc72b0, FormTemplateErrorsFields=io.swagger.models.ModelImpl@fedda362, FormTemplateFieldsColumns=io.swagger.models.ModelImpl@f38cb1e7, FormTemplateFieldsOptions=io.swagger.models.ModelImpl@f38cb1e7, FormTemplateFieldsVisibility=io.swagger.models.ModelImpl@a58bc8fa, FormTemplateFieldsVisibilityField=io.swagger.models.ModelImpl@bc66748f, FormTemplateOverview=io.swagger.models.ModelImpl@2432d2c1, GenerateEGAApiKeyResponse=io.swagger.models.ModelImpl@f00f3e0, GetCatalogueItemsResponseLocalizationsKeyword3758=io.swagger.models.ModelImpl@367d7fac, GetCatalogueResponseLocalizationsKeyword3741=io.swagger.models.ModelImpl@367d7fac, GetCatalogueTreeResponse=io.swagger.models.ModelImpl@8919cc5e, GetCatalogueTreeResponseRootsItemsLocalizationsKeyword3748=io.swagger.models.ModelImpl@367d7fac, GetCatalogueTreeResponseRootsLocalizationsKeyword3753=io.swagger.models.ModelImpl@367d7fac, GetConfigResponse=io.swagger.models.ModelImpl@59e4026c, GetConfigResponseExtraPagesTranslations=io.swagger.models.ModelImpl@7ab818e0, GetConfigResponseExtraPagesTranslationsKeyword3635=io.swagger.models.ModelImpl@e7c33ab9, GetConfigResponseOidcExtraAttributes=io.swagger.models.ModelImpl@de3f3f0f, GetPermissionsResponse=io.swagger.models.ModelImpl@dfc98b32, Handler=io.swagger.models.ModelImpl@8b5177da, Health=io.swagger.models.ModelImpl@74082251, HealthVersion=io.swagger.models.ModelImpl@1a4fb233, InvitationResponse=io.swagger.models.ModelImpl@7a1cdf0d, InviteDeciderCommand=io.swagger.models.ModelImpl@c179441b, InviteDeciderCommandDecider=io.swagger.models.ModelImpl@424b6a0d, InviteMemberCommand=io.swagger.models.ModelImpl@8d76d433, InviteMemberCommandMember=io.swagger.models.ModelImpl@424b6a0d, InviteReviewerCommand=io.swagger.models.ModelImpl@c8dd4581, InviteReviewerCommandReviewer=io.swagger.models.ModelImpl@424b6a0d, License=io.swagger.models.ModelImpl@51b0b5d8, LicenseLocalization=io.swagger.models.ModelImpl@28d8661b, LicenseLocalizations=io.swagger.models.ModelImpl@d00f9b97, LicenseLocalizationsKeyword3800=io.swagger.models.ModelImpl@22f1b782, LicensesLocalizations=io.swagger.models.ModelImpl@1973c13c, LicensesLocalizationsKeyword3797=io.swagger.models.ModelImpl@22f1b782, LocalizedInt=io.swagger.models.ModelImpl@c4d98c01, LocalizedString=io.swagger.models.ModelImpl@d4784243, MondoCode=io.swagger.models.ModelImpl@98b17673, MondoCodeFull=io.swagger.models.ModelImpl@f172bf0d, NewFieldTemplate=io.swagger.models.ModelImpl@ae2c1e46, OrganizationArchivedCommand=io.swagger.models.ModelImpl@eb38834, OrganizationEnabledCommand=io.swagger.models.ModelImpl@bf93b692, OrganizationFull=io.swagger.models.ModelImpl@6004fd5b, OrganizationFullReviewEmails=io.swagger.models.ModelImpl@385ad7ab, OrganizationId=io.swagger.models.ModelImpl@8d01a1f3, OrganizationOverview=io.swagger.models.ModelImpl@87ca4d23, RejectCommand=io.swagger.models.ModelImpl@ae9f1fcd, RemarkCommand=io.swagger.models.ModelImpl@aa513cca, RemoveMemberCommand=io.swagger.models.ModelImpl@c05287c4, RequestDecisionCommand=io.swagger.models.ModelImpl@fa40158a, RequestReviewCommand=io.swagger.models.ModelImpl@1f347634, Resource=io.swagger.models.ModelImpl@9f5bcd6, ResourceDuo=io.swagger.models.ModelImpl@167a8071, ResourceDuoCodesRestrictions=io.swagger.models.ModelImpl@7a5f4b03, ResourceDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, ResourceLicense=io.swagger.models.ModelImpl@962e9f1, ResourceLicensesLocalizations=io.swagger.models.ModelImpl@c1b2508e, ResourceLicensesLocalizationsKeyword3830=io.swagger.models.ModelImpl@22f1b782, ResourcesDuo=io.swagger.models.ModelImpl@167a8071, ResourcesDuoCodesRestrictions=io.swagger.models.ModelImpl@699881e0, ResourcesDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, ResourcesLicensesLocalizations=io.swagger.models.ModelImpl@11bc24ed, ResourcesLicensesLocalizationsKeyword3818=io.swagger.models.ModelImpl@22f1b782, Response3638AcceptedLicenses=io.swagger.models.ModelImpl@c9bd82bb, Response3638BlacklistResource=io.swagger.models.ModelImpl@f6f99b6f, Response3638CopiedFrom=io.swagger.models.ModelImpl@958365c2, Response3638CopiedTo=io.swagger.models.ModelImpl@ff4fdc44, Response3638InvitedMembers=io.swagger.models.ModelImpl@424b6a0d, Response3638ResourcesDuo=io.swagger.models.ModelImpl@14268312, Response3638ResourcesDuoCodesRestrictions=io.swagger.models.ModelImpl@2c87e605, Response3638ResourcesDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, Response3638Workflow=io.swagger.models.ModelImpl@7633ee49, Response3648AcceptedLicenses=io.swagger.models.ModelImpl@c9bd82bb, Response3648BlacklistResource=io.swagger.models.ModelImpl@f6f99b6f, Response3648CopiedFrom=io.swagger.models.ModelImpl@80bd47c7, Response3648CopiedTo=io.swagger.models.ModelImpl@80bd47c7, Response3648InvitedMembers=io.swagger.models.ModelImpl@424b6a0d, Response3648ResourcesDuo=io.swagger.models.ModelImpl@1671c6e0, Response3648ResourcesDuoCodesRestrictions=io.swagger.models.ModelImpl@9ddfbe68, Response3648ResourcesDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, Response3648Workflow=io.swagger.models.ModelImpl@fef38469, Response3658AcceptedLicenses=io.swagger.models.ModelImpl@c9bd82bb, Response3658BlacklistResource=io.swagger.models.ModelImpl@f6f99b6f, Response3658CopiedFrom=io.swagger.models.ModelImpl@80bd47c7, Response3658CopiedTo=io.swagger.models.ModelImpl@80bd47c7, Response3658InvitedMembers=io.swagger.models.ModelImpl@424b6a0d, Response3658ResourcesDuo=io.swagger.models.ModelImpl@1671c6e0, Response3658ResourcesDuoCodesRestrictions=io.swagger.models.ModelImpl@57207509, Response3658ResourcesDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, Response3658Workflow=io.swagger.models.ModelImpl@fef38469, Response3668AcceptedLicenses=io.swagger.models.ModelImpl@c9bd82bb, Response3668BlacklistResource=io.swagger.models.ModelImpl@f6f99b6f, Response3668CopiedFrom=io.swagger.models.ModelImpl@80bd47c7, Response3668CopiedTo=io.swagger.models.ModelImpl@80bd47c7, Response3668InvitedMembers=io.swagger.models.ModelImpl@424b6a0d, Response3668ResourcesDuo=io.swagger.models.ModelImpl@1671c6e0, Response3668ResourcesDuoCodesRestrictions=io.swagger.models.ModelImpl@27d3212e, Response3668ResourcesDuoCodesRestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, Response3668Workflow=io.swagger.models.ModelImpl@fef38469, Response3734Resource=io.swagger.models.ModelImpl@f6f99b6f, Response3778Errors=io.swagger.models.ModelImpl@36c05c48, Response3778ErrorsFields=io.swagger.models.ModelImpl@fedda362, Response3792Workflow=io.swagger.models.ModelImpl@3e37c467, Response3801ReviewEmails=io.swagger.models.ModelImpl@385ad7ab, Response3821Restrictions=io.swagger.models.ModelImpl@a8fe42f2, Response3821RestrictionsValues=io.swagger.models.ModelImpl@e48ea0af, Response3835LicensesLocalizations=io.swagger.models.ModelImpl@b9168bf5, Response3835LicensesLocalizationsKeyword3840=io.swagger.models.ModelImpl@22f1b782, ReturnCommand=io.swagger.models.ModelImpl@ae9f1fcd, ReviewCommand=io.swagger.models.ModelImpl@ae9f1fcd, Reviewer=io.swagger.models.ModelImpl@93ecc109, RevokeCommand=io.swagger.models.ModelImpl@ae9f1fcd, SaveAttachmentResponse=io.swagger.models.ModelImpl@fbfc023c, SaveDraftCommand=io.swagger.models.ModelImpl@6b011a7f, SaveDraftCommandFieldValues=io.swagger.models.ModelImpl@e76c420a, SaveDraftCommandFieldValuesValue=io.swagger.models.ModelImpl@47a9fe77, SubmitCommand=io.swagger.models.ModelImpl@f02b83, SuccessResponse=io.swagger.models.ModelImpl@9a201e24, UninviteMemberCommand=io.swagger.models.ModelImpl@62a3d982, UninviteMemberCommandMember=io.swagger.models.ModelImpl@424b6a0d, UpdateCategoryCommand=io.swagger.models.ModelImpl@1dfcd87b, UpdateUserSettings=io.swagger.models.ModelImpl@8393f6d7, User=io.swagger.models.ModelImpl@392323b3, UserSettings=io.swagger.models.ModelImpl@163a104d, UserSettingsEga=io.swagger.models.ModelImpl@743303b2, UserWithAttributes=io.swagger.models.ModelImpl@105faa2, V2License=io.swagger.models.ModelImpl@dd41c9eb, V2Resource=io.swagger.models.ModelImpl@e4cb38e6, Workflow=io.swagger.models.ModelImpl@8c00c370, WorkflowLicensesLocalizations=io.swagger.models.ModelImpl@138ea138, WorkflowLicensesLocalizationsKeyword3846=io.swagger.models.ModelImpl@22f1b782, WriteCatalogueItemLocalizations=io.swagger.models.ModelImpl@94727962}
  Exception: io.swagger.models.parameters.RefParameter cannot be cast to io.swagger.models.parameters.BodyParameter
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:962)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:841)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:462)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:777)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:307)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.ClassCastException: io.swagger.models.parameters.RefParameter cannot be cast to io.swagger.models.parameters.BodyParameter
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2744)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2375)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:911)
	... 5 more
```
